Время разбивать камни
htmlacademy-ecmascript/1526731-cinemaddict-14 pull request #3
Opened 2021-04-23 18:57 UTC by kkoroleva

2021-04-24 13:46 UTC, dtsaryov requested changes

2021-04-24 13:46 UTC, dtsaryov commented on src/main.js
> +} from './view/footer-stats.js';
В одну строку, пожалуйста. Слишком много места занимает, читаемости не добавляет

2021-04-24 13:46 UTC, dtsaryov commented on src/main.js
> +const renderBlock = (block, place, container) => {
`place` лучше сделать последним аргументом и дать ему значение по умолчанию (наиболее часто используемое)

2021-04-24 13:46 UTC, dtsaryov commented on src/view/film-card.js
> +};
Во-первых, это относится к компоненту списку карточек, а во-вторых давай попробуем сделать это все через `map` и `join`

2021-04-28 14:24 UTC, kkoroleva commented on src/view/film-card.js
> +};
Сделаю, но не уверена, что согласна. Сейчас у меня изначально строка. А так, будет массив, который надо сначала инициализировать, заполнить, а потом спрямить в строку. Зачем такие сложности, если под капотом все равно for + одна ненужная операция переведения в строку? Чтобы была всего одна строка? 
Как-то так, да? let cards = newArray(cardsCount).fill().map( ()=> getFilmCard()).join();

2021-04-28 21:59 UTC, merged